spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-44-206-197-71.compute-1.amazonaws.com/d6qfdlfb073c1q
  username: mzfjfybxihwmzm
  password: b97640fa7cb3ba674ce4db2d6d25db8c7a55cb96f65c68c71b8811889e3458ea
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: Application.spacesns-2023-secretKey
  #30 DAYS
  token.expired-time-ms: 2592000000

spring.redis.url: redis://:p49fdc05013b9abf3cad2a055ee48a4fe9b4464996119fee3562d9018b1e0268d@ec2-107-22-230-192.compute-1.amazonaws.com:30629