spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-44-194-92-192.compute-1.amazonaws.com/df8k2ntkfjlar3
  username: juoksxjgfjhfxm
  password: dec918cfa9be1240e4fb60d909777c4af39072c2205dfc0fefbfeb7ca1eb9553
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: Application.spacesns-2023-secretKey
  #30 DAYS
  token.expired-time-ms: 2592000000

spring.redis.url: redis://:p49fdc05013b9abf3cad2a055ee48a4fe9b4464996119fee3562d9018b1e0268d@ec2-107-22-230-192.compute-1.amazonaws.com:30629